version: '2'
services:
  db:
    image: rethinkdb:latest
    ports:  
      - "38080:8080"
  web:
    image: markwatsonatx/node-alpine:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && node node_modules/nodemon/bin/nodemon.js -L server.js"
    ports:
      - "33000:3000"
    depends_on:
      - db
